<?php

namespace App\Console\Commands;

use App\Models\Tenant;
use App\Services\DepreciationRunService;
use App\Support\BusinessTime;
use Illuminate\Console\Command;

/**
 * §3.12: "Generated by a scheduled monthly job." Loops every Tenant
 * explicitly (DepreciationRunService::runForPeriod() needs one, since
 * ledger commits and AccountingPeriod resolution are both per-tenant),
 * same monthly cadence as the Fixed Asset Register/Depreciation Schedule
 * reports this feeds. Idempotent per (asset|asset_component, period) -
 * safe to re-run.
 */
class RunMonthlyAssetDepreciation extends Command
{
    protected $signature = 'assets:run-monthly-depreciation';

    protected $description = "Post the current month's AssetDepreciationEntry rows for every tenant's in-use/under-maintenance assets.";

    public function handle(DepreciationRunService $depreciation): int
    {
        $period = BusinessTime::today();
        $total = 0;

        foreach (Tenant::all() as $tenant) {
            $total += $depreciation->runForPeriod($tenant, $period);
        }

        $this->info("Posted {$total} depreciation entry/entries across all tenants for {$period->format('Y-m')}.");

        return self::SUCCESS;
    }
}
