<?php

namespace App\Services;

use App\Models\Asset;
use App\Models\AssetComponent;
use App\Models\AssetDepreciationEntry;
use App\Models\Tenant;
use App\Support\Money;
use Carbon\CarbonInterface;
use Illuminate\Support\Facades\DB;

/**
 * §3.12: "Generated by a scheduled monthly job, one entry per asset per
 * period." Three depreciation methods, straight_line/sum_of_digits/
 * diminishing_balance - standard accounting formulas for each, since the
 * Sali Assets reference implementation's exact arithmetic isn't available
 * to port from directly (only its proven three-method shape and the
 * revaluation/disposal bug fixes it already caught, both already in
 * LedgerPostingService). Flagged as an explicit implementation choice,
 * not a silent assumption:
 * - straight_line: (purchase_cost - residual_value) / (useful_life_years * 12), constant every month.
 * - sum_of_digits: sum-of-years-digits, applied by month within each
 *   12-month year block (annual figure / 12), not re-derived monthly.
 * - diminishing_balance: NBV x (annual rate / 12), where the annual rate
 *   is derived from residual_value (1 - (residual/cost)^(1/life)) when a
 *   residual value is set, or the double-declining-balance convention
 *   (2/useful_life_years) when it's zero, since a rate derived from a
 *   zero residual is undefined.
 *
 * A run is idempotent per (asset|asset_component, period) - re-running a
 * period that already has an entry is a no-op, not a duplicate posting.
 * Depreciation never runs an asset below its residual_value - the last
 * run before full depreciation is capped to exactly close that gap.
 */
class DepreciationRunService
{
    public function __construct(private LedgerPostingService $ledger) {}

    public function runForPeriod(Tenant $tenant, CarbonInterface $period): int
    {
        $period = $period->copy()->startOfMonth();
        $count = 0;

        $assets = Asset::where('tenant_id', $tenant->id)
            ->whereIn('status', ['in_use', 'under_maintenance'])
            ->with('components')
            ->get();

        foreach ($assets as $asset) {
            if ($asset->components->isNotEmpty()) {
                foreach ($asset->components as $component) {
                    if ($this->runOne($tenant, $component, $period)) {
                        $count++;
                    }
                }
            } elseif ($this->runOne($tenant, $asset, $period)) {
                $count++;
            }
        }

        return $count;
    }

    private function runOne(Tenant $tenant, Asset|AssetComponent $subject, CarbonInterface $period): bool
    {
        $fkColumn = $subject instanceof Asset ? 'asset_id' : 'asset_component_id';

        $alreadyRun = AssetDepreciationEntry::where($fkColumn, $subject->id)
            ->where('period', $period->toDateString())
            ->exists();
        if ($alreadyRun) {
            return false;
        }

        $priorEntries = AssetDepreciationEntry::where($fkColumn, $subject->id)->orderBy('period')->get();
        $priorAccumulated = $priorEntries->isEmpty() ? Money::zero() : $priorEntries->last()->accumulated_depreciation;

        // sum_of_digits needs "how many months into the current schedule"
        // - restarted from schedule_reset_at (a revaluation or lifespan
        // change) rather than counted from acquisition. See the
        // assets/asset_components migrations' docblocks.
        // Compared as calendar-date strings, not Carbon instant
        // comparison - period is cast in the app's storage timezone
        // (UTC) while schedule_reset_at may come from BusinessTime
        // (Africa/Nairobi); comparing instants directly can flip the
        // result near midnight even when both represent the same date.
        $monthsAlreadyRun = $subject->schedule_reset_at
            ? $priorEntries->filter(fn (AssetDepreciationEntry $e) => $e->period->toDateString() >= $subject->schedule_reset_at->toDateString())->count()
            : $priorEntries->count();

        $nbvBeforeRun = $subject->purchase_cost->sub($priorAccumulated);
        if (! $nbvBeforeRun->greaterThan($subject->residual_value)) {
            return false; // already fully depreciated
        }

        $depreciableBase = $subject->purchase_cost->sub($subject->residual_value);
        $amount = $this->monthlyDepreciation($subject, $depreciableBase, $nbvBeforeRun, $monthsAlreadyRun);

        $maxAllowed = $nbvBeforeRun->sub($subject->residual_value);
        if ($amount->greaterThan($maxAllowed)) {
            $amount = $maxAllowed;
        }
        if (! $amount->isPositive()) {
            return false;
        }

        $newAccumulated = $priorAccumulated->add($amount);
        $newNbv = $subject->purchase_cost->sub($newAccumulated);

        DB::transaction(function () use ($tenant, $subject, $fkColumn, $period, $amount, $newAccumulated, $newNbv) {
            $entry = AssetDepreciationEntry::create([
                'tenant_id' => $tenant->id,
                $fkColumn => $subject->id,
                'period' => $period,
                'depreciation_amount_cents' => $amount,
                'accumulated_depreciation_cents' => $newAccumulated,
                'net_book_value_cents' => $newNbv,
            ]);

            $entryInput = $this->ledger->postDepreciationRun((string) $entry->id, $amount);
            $journalEntry = $this->ledger->commit($tenant, $entryInput, $period, null, $entry->id);

            $entry->update(['journal_entry_id' => $journalEntry->id]);
        });

        return true;
    }

    /**
     * Pure projection, no persistence - reused by both the real run above
     * and ReportingService's Depreciation Schedule "Planned" view.
     */
    public function monthlyDepreciation(Asset|AssetComponent $subject, Money $depreciableBase, Money $nbvBeforeRun, int $monthsAlreadyRun): Money
    {
        return match ($subject->depreciation_method) {
            'straight_line' => $this->straightLine($depreciableBase, $subject->useful_life_years),
            'sum_of_digits' => $this->sumOfDigits($depreciableBase, $subject->useful_life_years, $monthsAlreadyRun),
            'diminishing_balance' => $this->diminishingBalance($subject, $nbvBeforeRun),
            default => throw new \InvalidArgumentException("Unknown depreciation_method '{$subject->depreciation_method}'."),
        };
    }

    private function straightLine(Money $depreciableBase, int $usefulLifeYears): Money
    {
        $totalMonths = $usefulLifeYears * 12;

        return Money::fromCents((int) bcdiv((string) $depreciableBase->cents(), (string) $totalMonths, 0));
    }

    private function sumOfDigits(Money $depreciableBase, int $usefulLifeYears, int $monthsAlreadyRun): Money
    {
        $yearIndex = intdiv($monthsAlreadyRun, 12) + 1; // 1-based
        if ($yearIndex > $usefulLifeYears) {
            return Money::zero();
        }

        $sumOfDigits = $usefulLifeYears * ($usefulLifeYears + 1) / 2;
        $remainingYears = $usefulLifeYears - $yearIndex + 1;

        $annual = (int) bcdiv(bcmul((string) $depreciableBase->cents(), (string) $remainingYears, 0), (string) $sumOfDigits, 0);

        return Money::fromCents((int) bcdiv((string) $annual, '12', 0));
    }

    private function diminishingBalance(Asset|AssetComponent $subject, Money $nbvBeforeRun): Money
    {
        $annualRate = $subject->residual_value->isPositive()
            ? 1 - ($subject->residual_value->cents() / $subject->purchase_cost->cents()) ** (1 / $subject->useful_life_years)
            : 2 / $subject->useful_life_years;

        return $nbvBeforeRun->multiplyByRate($annualRate / 12);
    }
}
