<?php

use Illuminate\Foundation\Inspiring;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Schedule;

Artisan::command('inspire', function () {
    $this->comment(Inspiring::quote());
})->purpose('Display an inspiring quote');

// withoutOverlapping() on every scheduled job (architecture §1) - the
// pattern every later scheduled job (retention re-evaluation, monthly
// depreciation, statutory reminders, ...) reuses from here on.
Schedule::command('invitations:prune-expired')->daily()->withoutOverlapping();

// §3.6: "scheduled -> active fires automatically when block_start_date
// is reached ... not a manual click that site staff would routinely
// forget." Daily is sufficient granularity - block_start_date/
// block_end_date are dates, not datetimes.
Schedule::command('resource-assignments:advance-status')->daily()->withoutOverlapping();

// §5.4: re-evaluates every defects_liability Project's dlp_ready_to_close
// flag daily - see EvaluateDlpEligibility's own docblock for why the
// actual defects_liability -> closed transition stays manual.
Schedule::command('projects:evaluate-dlp-eligibility')->daily()->withoutOverlapping();

// §3.12: "Generated by a scheduled monthly job" - idempotent per period,
// so running it more than once in a month (a retry after a failure, for
// instance) never double-posts.
Schedule::command('assets:run-monthly-depreciation')->monthly()->withoutOverlapping();
