import approvalLimits from './approval-limits'
import appsAndPages from './apps-and-pages'
import assets from './assets'
import charts from './charts'
import dashboard from './dashboard'
import forms from './forms'
import hr from './hr'
import labourResourcing from './labour-resourcing'
import manufacturing from './manufacturing'
import others from './others'
import projects from './projects'
import salesBilling from './sales-billing'
import uiElements from './ui-elements'

export default [...dashboard, ...salesBilling, ...manufacturing, ...labourResourcing, ...projects, ...assets, ...hr, ...approvalLimits, ...appsAndPages, ...uiElements, ...forms, ...charts, ...others]
