<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * §3.12: "Generated by a scheduled monthly job, one entry per asset per
 * period - this is what actually posts to the ledger and what the
 * Balance Sheet's Fixed Assets figure is computed from." Exactly one of
 * asset_id/asset_component_id is set per row, matching whether the parent
 * Asset has AssetComponent rows or depreciates on its own fields directly.
 * Append-only once posted (same immutable-historical-fact principle as
 * JournalEntry/StockLedger) - a correction is a later period's entry, not
 * an edit to this one.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('asset_depreciation_entries', function (Blueprint $table) {
            $table->id();
            $table->foreignId('tenant_id')->constrained()->cascadeOnDelete();
            $table->foreignId('asset_id')->nullable()->constrained()->cascadeOnDelete();
            $table->foreignId('asset_component_id')->nullable()->constrained('asset_components')->cascadeOnDelete();
            $table->date('period');
            $table->bigInteger('depreciation_amount_cents');
            $table->bigInteger('accumulated_depreciation_cents');
            $table->bigInteger('net_book_value_cents');
            $table->foreignId('journal_entry_id')->nullable()->constrained()->nullOnDelete();
            $table->timestamp('created_at')->useCurrent();

            $table->unique(['asset_id', 'period']);
            $table->unique(['asset_component_id', 'period']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('asset_depreciation_entries');
    }
};
