<?php

namespace App\Models;

use App\Casts\MoneyCast;
use App\Models\Scopes\TenantScope;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Model;

/** §3.12: append-only, generated by the monthly depreciation run - never edited once posted. */
class AssetDepreciationEntry extends Model
{
    const UPDATED_AT = null;

    protected $fillable = [
        'tenant_id',
        'asset_id',
        'asset_component_id',
        'period',
        'depreciation_amount_cents',
        'accumulated_depreciation_cents',
        'net_book_value_cents',
        'journal_entry_id',
    ];

    protected $hidden = ['depreciation_amount_cents', 'accumulated_depreciation_cents', 'net_book_value_cents'];

    protected $appends = ['depreciation_amount', 'accumulated_depreciation', 'net_book_value'];

    protected function casts(): array
    {
        return [
            'period' => 'date',
            'depreciation_amount_cents' => MoneyCast::class,
            'accumulated_depreciation_cents' => MoneyCast::class,
            'net_book_value_cents' => MoneyCast::class,
        ];
    }

    protected function depreciationAmount(): Attribute
    {
        return Attribute::make(get: fn () => $this->depreciation_amount_cents);
    }

    protected function accumulatedDepreciation(): Attribute
    {
        return Attribute::make(get: fn () => $this->accumulated_depreciation_cents);
    }

    protected function netBookValue(): Attribute
    {
        return Attribute::make(get: fn () => $this->net_book_value_cents);
    }

    protected static function booted(): void
    {
        static::addGlobalScope(new TenantScope);
    }

    public function asset()
    {
        return $this->belongsTo(Asset::class);
    }

    public function assetComponent()
    {
        return $this->belongsTo(AssetComponent::class);
    }

    public function journalEntry()
    {
        return $this->belongsTo(JournalEntry::class);
    }

    public function tenant()
    {
        return $this->belongsTo(Tenant::class);
    }
}
